env: "local"    # окружение приложения(local, dev, prod)
storage_path: "./storage/storage.db"    #путь до бд (SQLLITE)
http_server:
  address: "localhost:8082"
  timeout: 4s    #время на чтение запроса и отправку ответа
  idle_timeout: 60s    #время соединения с клиентом


